version: "3"
services:
  front:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    tty: true
    ports:
      - "3000:3000" # 開発用
      - "4000:4000" # 本番用
    volumes:
      - ./frontend/app:/app # ./app/{プロジェクト名}:/app
    command: yarn dev
